In [1]:
from pathlib import Path
import polars as pl

DATA_DIR = Path("..") / "data"
RAW_CSV  = DATA_DIR / "stop_geometry.csv"
OUT_PATH = DATA_DIR / "stop_geometry.parquet"

In [2]:
df = pl.read_csv(RAW_CSV)
print(f"Loaded:  {len(df):,} rows")
print(df.schema)
df.head(5)

Loaded:  3,583 rows
Schema([('ort_nr', Int64), ('stop_name', String), ('stop_name_short', String), ('latitude', Float64), ('longitude', Float64), ('vvo_nr', Int64)])

shape: (5, 6)
┌────────┬──────────────────────┬─────────────────┬───────────┬───────────┬────────┐
│ ort_nr ┆ stop_name            ┆ stop_name_short ┆ latitude  ┆ longitude ┆ vvo_nr │
│ ---    ┆ ---                  ┆ ---             ┆ ---       ┆ ---       ┆ ---    │
│ i64    ┆ str                  ┆ str             ┆ f64       ┆ f64       ┆ i64    │
╞════════╪══════════════════════╪═════════════════╪═══════════╪═══════════╪════════╡
│ 100301 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072467 ┆ 13.714895 ┆ 523001 │
│ 100302 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072544 ┆ 13.7149   ┆ 523001 │
│ 100303 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072495 ┆ 13.714966 ┆ 523001 │
│ 100304 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072572 ┆ 13.714978 ┆ 523001 │
│ 100401 ┆ Messe Dresden        ┆ MES             ┆ 51.069945 ┆ 13.714366 ┆ 522001 │
└────────┴──────────────────────┴─────────────────┴───────────┴───────────┴────────┘

In [3]:
df_unique = df.unique(maintain_order=True)
print(f"Before: {len(df):,}  |  After dedup: {len(df_unique):,}  |  Removed: {len(df) - len(df_unique):,}")
df_unique.head(5)

Before: 3,583  |  After dedup: 3,583  |  Removed: 0

shape: (5, 6)
┌────────┬──────────────────────┬─────────────────┬───────────┬───────────┬────────┐
│ ort_nr ┆ stop_name            ┆ stop_name_short ┆ latitude  ┆ longitude ┆ vvo_nr │
│ ---    ┆ ---                  ┆ ---             ┆ ---       ┆ ---       ┆ ---    │
│ i64    ┆ str                  ┆ str             ┆ f64       ┆ f64       ┆ i64    │
╞════════╪══════════════════════╪═════════════════╪═══════════╪═══════════╪════════╡
│ 100301 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072467 ┆ 13.714895 ┆ 523001 │
│ 100302 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072544 ┆ 13.7149   ┆ 523001 │
│ 100303 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072495 ┆ 13.714966 ┆ 523001 │
│ 100304 ┆ Messe, Gleisschleife ┆ MEG             ┆ 51.072572 ┆ 13.714978 ┆ 523001 │
│ 100401 ┆ Messe Dresden        ┆ MES             ┆ 51.069945 ┆ 13.714366 ┆ 522001 │
└────────┴──────────────────────┴─────────────────┴───────────┴───────────┴────────┘

In [4]:
df_unique.write_parquet(OUT_PATH)
print(f"Saved → {OUT_PATH}  ({OUT_PATH.stat().st_size / 1e3:.1f} KB)")

Saved → ../data/stop_geometry.parquet  (81.8 KB)